#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "Building envkey-source..."
cd $SCRIPT_DIR/../sdks/envkey-source
go build

echo "Copying envkey-source binary to tests dir..."
cp envkey-source ../../app/tests/envkey-source