#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )


echo "installing global go deps..."
sleep 2
go install -a -v github.com/go-bindata/go-bindata/...@v3.1.2
echo ""
echo "--------"
echo ""

echo "installing global npm deps..."
sleep 2
npm i -g ts-node@10.0.0 npm-check-updates@12.1.0 nodemon@2.0.15
echo ""
echo "--------"
echo ""

cd $SCRIPT_DIR/../..
echo "installing shared npm deps..."
echo $(pwd)
sleep 2
npm i && npm prune
echo ""
echo "--------"
echo ""

cd $SCRIPT_DIR/../app
echo "installing public npm deps..."
echo $(pwd)
sleep 2
npm i && npm prune
echo ""
echo "--------"
echo ""