#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR/../..
echo "auditing SHARED npm deps..."
echo $(pwd)
sleep 2
npm audit --production
echo ""
echo "--------"
echo ""

cd $SCRIPT_DIR/../app
echo "auditing PUBLIC npm deps..."
echo $(pwd)
sleep 2
npm audit --production
