export const CRYPTO_ASYMMETRIC_BATCH_SIZE = 500;
export const CRYPTO_ASYMMETRIC_BATCH_DELAY_MS = 70;
export const CRYPTO_ASYMMETRIC_STATUS_INTERVAL = 100;

export const CRYPTO_SYMMETRIC_BATCH_SIZE = 500;
export const CRYPTO_SYMMETRIC_BATCH_DELAY_MS = 70;
export const CRYPTO_SYMMETRIC_STATUS_INTERVAL = 100;
